plugins {
    id 'java'
    id 'application'
}

group = 'com.danielbohry'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.danielbohry.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.danielbohry.Main'
    }
}

test {
    useJUnitPlatform()
}